/**
 * Copyright (c) 2017 CEA.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *  Contributors:
 *     CEA - initial API and implementation and/or initial documentation
 */
/**
 * generated by Xtext 2.9.1
 */
package org.eclipse.sensinact.studio.language.sensinact;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>DSL Resource</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.sensinact.studio.language.sensinact.DSL_Resource#getGatewayID <em>Gateway ID</em>}</li>
 *   <li>{@link org.eclipse.sensinact.studio.language.sensinact.DSL_Resource#getDeviceID <em>Device ID</em>}</li>
 *   <li>{@link org.eclipse.sensinact.studio.language.sensinact.DSL_Resource#getServiceID <em>Service ID</em>}</li>
 *   <li>{@link org.eclipse.sensinact.studio.language.sensinact.DSL_Resource#getResourceID <em>Resource ID</em>}</li>
 * </ul>
 *
 * @see org.eclipse.sensinact.studio.language.sensinact.SensinactPackage#getDSL_Resource()
 * @model
 * @generated
 */
public interface DSL_Resource extends DSL_REF
{
  /**
   * Returns the value of the '<em><b>Gateway ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Gateway ID</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gateway ID</em>' attribute.
   * @see #setGatewayID(String)
   * @see org.eclipse.sensinact.studio.language.sensinact.SensinactPackage#getDSL_Resource_GatewayID()
   * @model
   * @generated
   */
  String getGatewayID();

  /**
   * Sets the value of the '{@link org.eclipse.sensinact.studio.language.sensinact.DSL_Resource#getGatewayID <em>Gateway ID</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Gateway ID</em>' attribute.
   * @see #getGatewayID()
   * @generated
   */
  void setGatewayID(String value);

  /**
   * Returns the value of the '<em><b>Device ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Device ID</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Device ID</em>' attribute.
   * @see #setDeviceID(String)
   * @see org.eclipse.sensinact.studio.language.sensinact.SensinactPackage#getDSL_Resource_DeviceID()
   * @model
   * @generated
   */
  String getDeviceID();

  /**
   * Sets the value of the '{@link org.eclipse.sensinact.studio.language.sensinact.DSL_Resource#getDeviceID <em>Device ID</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Device ID</em>' attribute.
   * @see #getDeviceID()
   * @generated
   */
  void setDeviceID(String value);

  /**
   * Returns the value of the '<em><b>Service ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Service ID</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Service ID</em>' attribute.
   * @see #setServiceID(String)
   * @see org.eclipse.sensinact.studio.language.sensinact.SensinactPackage#getDSL_Resource_ServiceID()
   * @model
   * @generated
   */
  String getServiceID();

  /**
   * Sets the value of the '{@link org.eclipse.sensinact.studio.language.sensinact.DSL_Resource#getServiceID <em>Service ID</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Service ID</em>' attribute.
   * @see #getServiceID()
   * @generated
   */
  void setServiceID(String value);

  /**
   * Returns the value of the '<em><b>Resource ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Resource ID</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Resource ID</em>' attribute.
   * @see #setResourceID(String)
   * @see org.eclipse.sensinact.studio.language.sensinact.SensinactPackage#getDSL_Resource_ResourceID()
   * @model
   * @generated
   */
  String getResourceID();

  /**
   * Sets the value of the '{@link org.eclipse.sensinact.studio.language.sensinact.DSL_Resource#getResourceID <em>Resource ID</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Resource ID</em>' attribute.
   * @see #getResourceID()
   * @generated
   */
  void setResourceID(String value);

} // DSL_Resource
