/*
 * generated by Xtext 2.12.0
 */
package org.eclipse.sensinact.studio.language.ide


/**
 * Use this class to register ide components.
 */
class SensinactIdeModule extends AbstractSensinactIdeModule {
}
