/**
 * Copyright (c) 2017 CEA.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *  Contributors:
 *     CEA - initial API and implementation and/or initial documentation
 */
/*
 * generated by Xtext 2.9.1
 */
package org.eclipse.sensinact.studio.language.ui.tests;

import com.google.inject.Injector;
import org.eclipse.sensinact.studio.language.sensinact.ui.internal.SensinactActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class SensinactUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SensinactActivator.getInstance().getInjector("org.eclipse.sensinact.studio.language.Sensinact");
	}

}
